name: Update Directory Listings

on:
  push:
    paths:
      - 'Addons/**'
      - '**/update-readme.yml'
    branches:
      - main # oder der Name des Hauptzweigs Ihres Repos

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Update README with directories
      run: |
        echo "Listing directories and subdirectories with hierarchy..."
        awk '/<!-- DIR_LIST_START -->/{print; flag=1; next} /<!-- DIR_LIST_END -->/{flag=0; print; next} flag{next} 1' README.md > temp_readme.md && mv temp_readme.md README.md
        touch temp_dirs.md
        find Addons -type d -not -path "Addons/*/stream" -not -path "Addons/*/data"| cut -c 1- | sort | grep -vE '^\.\|_\|/stream\|/data' | while IFS= read -r dir; do
          depth=$(echo "$dir" | tr -cd '/' | wc -c)
          indent=$(printf '   %.0s' $(seq 1 $depth))
          display_name=$(basename "$dir")
          echo "${indent}- ${display_name}" >> temp_dirs.md
        done
        awk '/<!-- DIR_LIST_START -->/{print; system("cat temp_dirs.md"); print "<!-- DIR_LIST_END -->"; next} 1' README.md > temp_readme.md && mv temp_readme.md README.md
        rm temp_dirs.md

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        if git commit -m "Automatically update directory listings"; then
          git push
        fi
