name: Update README
on:
  push:
    branches:
      - main
jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update README
        run: |
          echo "### Addons"
          echo ""
          for dir in $(find ./Addons -type d); do
            echo "- $dir"
          done
          echo ""
          echo "### End of Addons"
          gh-pages-update README.md
