name: Update README

on:
  push:
    paths:
    - '**/'
    - '.github/workflows/update-readme.yml'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.MY_GITHUB_TOKEN }}
        
    - name: Update README with directories
      run: |
       echo "Listing directories and subdirectories with hierarchy, excluding '.git', '.github', 'stream', and 'data'..."

       # Entfernen des alten Eintrags zwischen den Markierungen
       awk '/<!-- DIR_LIST_START -->/{print; flag=1; next} /<!-- DIR_LIST_END -->/{flag=0; print; next} flag{next} 1' README.md > temp_readme.md && mv temp_readme.md README.md
      
       # Erstelle eine temporäre Datei für die Verzeichnisse
       touch temp_dirs.md
      
       # Finde alle Ordner, schließe die spezifizierten Ordner und deren Unterordner aus und schreibe sie in die temporäre Datei
       find . -type d | cut -c 3- | grep -vE '^\.\|_\|/.git\|/.github\|/workflows\|/stream\|/data' | while IFS= read -r dir; do
         depth=$(echo "$dir" | tr -cd '/' | wc -c)
         indent=$(printf '   %.0s' $(seq 1 $depth))
         # Extrahiere den Ordnernamen für die Anzeige
         display_name=$(basename "$dir")
         echo "${indent}- ${display_name}" >> temp_dirs.md
       done
  
       # Füge den neuen Eintrag zwischen den Markierungen hinzu
       awk '/<!-- DIR_LIST_START -->/{print; system("cat temp_dirs.md"); print "<!-- DIR_LIST_END -->"; next} 1' README.md > temp_readme.md && mv temp_readme.md README.md
      
       # Lösche die temporäre Datei
       rm temp_dirs.md
        
    - name: Commit and push if changed
      run: |
       git diff
       git config --global user.name 'GitHub Actions'
       git config --global user.email 'actions@github.com'
       git add README.md
       git status
       git commit -m "Automatically update README with directory list"
       git remote set-url origin https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/TrierRP/Vehicles.git
       git push origin HEAD:main || echo "No changes to commit/push"
